USE customer_behavior;
select * from customer limit 20;
-- Q1. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied`= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q2. Compare the average Purchase Amounts between Standard and Express Shipping. give code
SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase_amount
FROM customer
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q3. Which customers used a discount but still spent more than the average purchase amount?
SELECT `Customer ID`,
       `Purchase Amount (USD)`
FROM customer
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` > (
        SELECT AVG(`Purchase Amount (USD)`)
        FROM customer
      );
	
-- Q4. Which shipping type generates the highest total revenue?
SELECT `Shipping Type`,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY `Shipping Type`
ORDER BY total_revenue DESC
LIMIT 1;

-- Q5. Segment customers into New, Returning, and Loyal based on previous purchases
WITH customer_segments AS (
    SELECT `Customer ID`,
           `Previous Purchases`,
           CASE 
               WHEN `Previous Purchases` = 1 THEN 'New'
               WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_segment;

-- Q6. What is the total revenue generated by male vs female customers?
SELECT `Gender`,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY `Gender`;

-- Q7. Find customers whose purchase amount is in the top 10% (high spenders)
SELECT `Customer ID`,
       `Purchase Amount (USD)`
FROM (
    SELECT `Customer ID`,
           `Purchase Amount (USD)`,
           NTILE(10) OVER (ORDER BY `Purchase Amount (USD)` DESC) AS percentile_group
    FROM customer
) t
WHERE percentile_group = 1;

-- Q8. Which category has the highest average review rating?
SELECT `Category`,
       ROUND(AVG(`Review Rating`), 2) AS avg_rating
FROM customer
GROUP BY `Category`
ORDER BY avg_rating DESC
LIMIT 1;

-- Q9. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT `Category`,
           `Item Purchased`,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY `Category`
               ORDER BY COUNT(*) DESC
           ) AS item_rank
    FROM customer
    GROUP BY `Category`, `Item Purchased`
)

SELECT `Category`,
       `Item Purchased`,
       total_orders,
       item_rank
FROM item_counts
WHERE item_rank <= 3;

-- Q10. Do subscribed customers spend more? Compare avg spend and total revenue
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q11. Which age group has the highest average purchase amount?
SELECT `Age`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase_amount
FROM customer
GROUP BY `Age`
ORDER BY avg_purchase_amount DESC
LIMIT 1;

-- Q12. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM (
    SELECT `Purchase Amount (USD)`,
           CASE 
               WHEN Age < 25 THEN '18-24'
               WHEN Age BETWEEN 25 AND 34 THEN '25-34'
               WHEN Age BETWEEN 35 AND 44 THEN '35-44'
               WHEN Age BETWEEN 45 AND 54 THEN '45-54'
               ELSE '55+'
           END AS age_group
    FROM customer
) t
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q13. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS avg_rating
FROM customer
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC
LIMIT 5;

-- Q14. Are repeat buyers (>5 purchases) more likely to subscribe?
SELECT `Subscription Status`,
       COUNT(*) AS repeat_buyers
FROM customer
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q15. What is the average review rating for discounted vs non-discounted purchases?
SELECT `Discount Applied`,
       ROUND(AVG(`Review Rating`), 2) AS avg_rating
FROM customer
GROUP BY `Discount Applied`;